# Generated by Django 5.1.1 on 2024-09-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='compatible_products',
            field=models.ManyToManyField(blank=True, related_name='compatibility', to='store.product'),
        ),
    ]
